learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('myapp/',include('myapp.urls')),
    path('logout/',views.user_logout,name='Logout'),
    path('special/',views.special, name='Special'),
]

learning_users/myapp/urls.py
from django.urls import path,include
from myapp import views

app_name = 'myapp'

urlpatterns = [
    
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

learning_users/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# SuperUserInformation
# User: Jose
# Email: training@pieriandata.com
# Password: testpassword

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='myapp/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

learning_users/myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/myapp/views.py
from django.shortcuts import render
from myapp.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'myapp/index.html')

@login_required
def special(request):
    return HttpResponse('your are logged in !!')



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST" :

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)

            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
        
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'myapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
    
def user_login(request):

        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username,password=password)

            if user:

                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return HttpResponse('YOUR ACCOUNT NOT ACTIVE')
            else:
                print('Somone tried login as failed')
                print("Username: {} and password{}".format(username,password))
                return HttpResponse('invalid credentails')
        else:
            return render (request,'myapp/login.html',{})

            

learning_users/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%url 'index'%}"> DJANGO </a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}"> ADMIN </a></li>
                <li><a class="navbar-link" href="{% url 'myapp:register' %}"> Register</a></li>

                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'Logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a class='nav-link' href="{% url 'myapp:user_login' %}"> Login </a>
                </li>

                {% endif %}




            </ul>
        </div>

    </nav>
    <div class="container">
        {% block body_block%} {% endblock %}
    </div>

</body>

</html>

learning_users/templates/myapp/index.html
<!DOCTYPE html> {% extends "myapp/base.html"%} {% block body_block %}

<div class="jumbotron">
    <h1>DJANGO LEVEL FIVE</h1>
</div>

{% endblock %}

learning_users/templates/myapp/login.html
{% extends 'myapp/base.html'%} {% block body_block %}

<div class="jumbotron">
    <h1>Please Login </h1>
    <form action="{% url 'myapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="login">
    </form>
</div>
{% endblock %}

learning_users/templates/myapp/registration.html
{% extends "myapp/base.html" %} {% load static %} {% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %} {{ user_form.as_p }} {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>

        {% endif %}

    </div>

</div>

{% endblock %}